### ISSUE TITLE
Fisher: Support for .fish files outside a functions directory is deprecated

### ISSUE THREAD

**Issue by jeremymeyers** [rodrigobdz/fish-apple-touchbar#10]
**Describe the bug**
When trying to update to the latest version, got the error above.  May need refactoring?
 
Caused by https://github.com/jorgebucaran/fisher/issues/651

**Comment by rodrigobdz** [comment]
@jeremymeyers Thanks for reporting this issue related to https://github.com/jorgebucaran/fisher/issues/651. Opened PR https://github.com/rodrigobdz/fish-apple-touchbar/pull/11 to fix this.

Please help reviewing it.
