### ISSUE TITLE
not compatible with fzf.fish

### ISSUE THREAD

**Issue by fredericrous** [rodrigobdz/fish-apple-touchbar#13]
**Describe the bug**
When I use fzf.fish, I am getting extra lines containing "1337;SetKeyLabel=" shown on the attached screenshot

**To Reproduce**
1. fisher install rodrigobdz/fish-apple-touchbar plugin
2. fisher install PatrickF1/fzf.fish
3. Ctrl+R

**Expected behavior**
I'd like this extra output seen in the screenshot to go away.
Would it be possible that fish-apple-touchbar is not cleaning its output correctly?
Or maybe I didn't configure it correctly (see my config in section *Aditionnal Information*)

**Screenshots**
![image](https://user-images.githubusercontent.com/702227/124274144-ceda5a00-db38-11eb-9ce9-3e05c3f3bbc5.png)

**Desktop (please complete the following information):**
 - OS: Mac Big Sur 11.4
 - Fish: 3.3.0
 - iTerm2: 3.4.6

**Aditionnal Information**
I configured fish-apple-touchbar like so:

```sh
cat  ~/.config/fish/conf.d/touchbar.fish
__fish_apple_touchbar_bind_key_custom 1 '👈' 'prevd' '-s'
__fish_apple_touchbar_bind_key_custom 2 '🗄 jump' 'cdh' '-s'
```

**Comment by rodrigobdz** [comment]
Hi, @fredericrous! Thanks for reporting. 

I just looked into it and I found a [similar issue](https://github.com/PatrickF1/fzf.fish/issues/183) with `fzf`'s history containing `bind` commands. I'm afraid this has to be solved in [PatrickF1/fzf.fish](https://github.com/PatrickF1/fzf.fish).

The extra lines you are seeing containing `SetKeyLabel` are [iTerm2 proprietary escape codes](https://iterm2.com/documentation-escape-codes.html), which provide an interface to customize the Touch Bar. That interface is used in this plugin.

**Comment by fredericrous** [comment]
Thank you for having looked at this @rodrigobdz ! I'll open an issue there then

**Comment by fredericrous** [comment]
I found a workaround... Instead of having a file `conf.d/touchbar.fish` I moved everything into `config.fish` and the issue disappeared 🤯

**Comment by rodrigobdz** [comment]
That's interesting. I wonder if all the plugin features still work.

I created `conf.d/fish_apple_touchbar.fish` a while ago after [this](https://github.com/jorgebucaran/fisher/issues/651#issuecomment-762808325) announcement, which required plugins to update their file structure.

**Comment by kidonng** [comment]
@rodrigobdz This is not a bug with either plugins, but OP's own config, see https://github.com/PatrickF1/fzf.fish/issues/184#issuecomment-874074717
