### ISSUE TITLE
Not working when using vim bindings

### ISSUE THREAD

**Issue by tommyknows** [rodrigobdz/fish-apple-touchbar#3]
**Describe the bug**

The plugin does not seem to work when using fish with the vi-key-bindings (https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_vi_key_bindings.fish) and in insert mode.

**To Reproduce**
1. Enable vi-keybindings (`fish_vi_key_bindings`)
2. See that pressing the touchbar keys do not do anything (the bell is triggered though)
3. press "escape" to get into normal mode (out of insert mode)
4. press the touchbar key again and see that it works :-)

**Expected behavior**
I'd expect it to work in insert-mode too.

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 10.14.6
 - Fish: 3.0.2

**Comment by rodrigobdz** [comment]
@tommyknows Thanks for reporting this. Would you be interested in giving this a try?

**Comment by tommyknows** [comment]
Found a hint at this: 
https://github.com/jethrokuan/fzf/pull/106/files

Could you try if this still works for you?
https://github.com/tommyknows/fish-apple-touchbar/tree/vim-insert

**Comment by rodrigobdz** [comment]
Nice! I'll take a look at the PR.

**Comment by tommyknows** [comment]
PR is #5, #4 is something else 🙂

**Comment by rodrigobdz** [comment]
Can we close this issue @tommyknows?

**Comment by tommyknows** [comment]
Yes, I think so. Thank you.

**Comment by rodrigobdz** [comment]
Thank _you_ for your contribution!
