### ISSUE TITLE
Default key bindings just displays the touch code

### ISSUE THREAD

**Issue by glove99** [rodrigobdz/fish-apple-touchbar#7]
**Describe the bug**
The touchbar only echos the key code to the terminal. The actual command does not run. I am guessing the binding is not happening like it should.

**To Reproduce**
1. Go to iterm2 
2. Touch 'second view.'
3. Touch 'pwd'
4. Terminal displays 0Q

**Expected behavior**
The touchbar command should run.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Version 10.15.6 (19G2021)

**Additional context**
I tried with Tide installed and uninstalled and the problem persisted. I have completely closed iterm2 as well. I am not sure where to start debugging this problem. I haven't worked with fish packages before. Any ideas where I should start looking? Thanks!

**Comment by rodrigobdz** [comment]
@glove99 Thank you for filing the bug report. 
Currently I'm out of bandwidth to personally fix this issue. However, I'd be glad to review a related PR

**Comment by glove99** [comment]
I know the feeling. If I can find some time to dig into it, I will.

**Comment by rodrigobdz** [comment]
@glove99 I can reproduce the issue. To debug it is helpful to run one of the [functions](https://github.com/rodrigobdz/fish-apple-touchbar/blob/826e3228697878bbe4790e8b3c32872c09ab8c4d/functions/fish-apple-touchbar.fish#L5-L10) manually which configure the touch bar and enable debug mode in fish shell by running:

```sh
set fish_trace 1
```
